<<<<<<< HEAD
[[build]]
  command = "yanr build"
=======
[build]
  command = "yarn build && export"
>>>>>>> Tasks
  publish = "/.next"
  base = "/"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
[[plugins]]
  package = "@netlify/plugin-nextjs"
